// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: SimpleMessage.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SimpleMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Email         string `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	Age           int32  `protobuf:"varint,4,opt,name=Age,proto3" json:"Age,omitempty"`
	IsAProgrammer bool   `protobuf:"varint,5,opt,name=IsAProgrammer,proto3" json:"IsAProgrammer,omitempty"`
}

func (x *SimpleMessage) Reset() {
	*x = SimpleMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SimpleMessage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimpleMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleMessage) ProtoMessage() {}

func (x *SimpleMessage) ProtoReflect() protoreflect.Message {
	mi := &file_SimpleMessage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleMessage.ProtoReflect.Descriptor instead.
func (*SimpleMessage) Descriptor() ([]byte, []int) {
	return file_SimpleMessage_proto_rawDescGZIP(), []int{0}
}

func (x *SimpleMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SimpleMessage) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SimpleMessage) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *SimpleMessage) GetIsAProgrammer() bool {
	if x != nil {
		return x.IsAProgrammer
	}
	return false
}

var File_SimpleMessage_proto protoreflect.FileDescriptor

var file_SimpleMessage_proto_rawDesc = []byte{
	0x0a, 0x13, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x71, 0x0a, 0x0d, 0x53,
	0x69, 0x6d, 0x70, 0x6c, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x41, 0x67, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x41, 0x67, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x49, 0x73, 0x41, 0x50,
	0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x6d, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0d, 0x49, 0x73, 0x41, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x6d, 0x65, 0x72, 0x42, 0x08,
	0x5a, 0x06, 0x2f, 0x3b, 0x6d, 0x61, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_SimpleMessage_proto_rawDescOnce sync.Once
	file_SimpleMessage_proto_rawDescData = file_SimpleMessage_proto_rawDesc
)

func file_SimpleMessage_proto_rawDescGZIP() []byte {
	file_SimpleMessage_proto_rawDescOnce.Do(func() {
		file_SimpleMessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_SimpleMessage_proto_rawDescData)
	})
	return file_SimpleMessage_proto_rawDescData
}

var file_SimpleMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SimpleMessage_proto_goTypes = []interface{}{
	(*SimpleMessage)(nil), // 0: main.SimpleMessage
}
var file_SimpleMessage_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_SimpleMessage_proto_init() }
func file_SimpleMessage_proto_init() {
	if File_SimpleMessage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_SimpleMessage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimpleMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_SimpleMessage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SimpleMessage_proto_goTypes,
		DependencyIndexes: file_SimpleMessage_proto_depIdxs,
		MessageInfos:      file_SimpleMessage_proto_msgTypes,
	}.Build()
	File_SimpleMessage_proto = out.File
	file_SimpleMessage_proto_rawDesc = nil
	file_SimpleMessage_proto_goTypes = nil
	file_SimpleMessage_proto_depIdxs = nil
}
